Area.create(name: 'バンクーバー:Vancouver')
Area.create(name: 'カルガリー:Calgary')
Area.create(name: 'トロント:Toronto')
Area.create(name: 'モントリオール:Montreal')
Category.create(name: 'レント/シェア/ホームステイ:rent')
Category.create(name: '求人情報:jobs')
Category.create(name: 'コミュニティー:community')
Category.create(name: '習い事:lessons')
Category.create(name: 'イベント:events')
Category.create(name: '売ります/買います:buy/sell')

allarea = BArea.create(name: '全地域:All area')
vancouver, calgary, toronto, montreal = allarea.children.create([{name: 'バンクーバー:Vancouver'}, {name: 'カルガリー:Calgary'}, {name: 'トロント:Toronto'}, {name: 'モントリオール:Montreal'}])
allcategory = BCategory.create(name: '全カテゴリー:All category')
allcategory.children.create(name: '旅行・観光:travel')
allcategory.children.create(name: '留学・ワーホリ:study abroad')
allcategory.children.create(name: '移民・ワーク・ビザ:immigration')
allcategory.children.create(name: '生活:life')
allcategory.children.create(name: 'フリー:free')
allcategory.children.create(name: 'グルメ:food')
allcategory.children.create(name: '恋愛:love')
allcategory.children.create(name: '子育て・育児:child care')
allcategory.children.create(name: 'サークル・仲間探し:group')
allcategory.children.create(name: '仕事:work')
